GET https://switchiq-api.vercel.app/calls?start_time=2024-04-28&end_time=2024-05-03&page_size=16384

###
GET https://switchiq-api.vercel.app/calls?start_time=2024-04-28&end_time=2024-05-03&page_size=200

###
GET https://switchiq-api.vercel.app/calls?start_time=2024-04-28&end_time=2024-05-02&page_size=6716
###
GET https://switchiq-api.vercel.app/calls?start_time=2024-04-28&end_time=2024-05-02&page_size=8192
###
GET https://switchiq-api.vercel.app/calls?start_time=2024-04-28&end_time=2024-05-02&page_size=20000
###
GET https://switchiq-api.vercel.app/calls?start_time=2024-04-28&end_time=2024-05-02&page_size=20000&page=2

###
GET https://switchiq-api.vercel.app/calls?start_time=2024-04-28&end_time=2024-05-03&page_size=1952&page=2

###

GET https://switchiq-api.vercel.app/calls?start_time=2024-04-28&end_time=2024-05-03

###
GET https://switchiq-api.vercel.app/calls?start_time=2024-04-28 21:58:34

###
GET https://switchiq-api.vercel.app/frequent_dids?page_size=20000&page=0