import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '@/components/overview/figures/lead-map/leadMapStyles.css'
import '@/components/overview/figures/globalTableStyles.css'
import Header from '@/components/header/Header'
import { DateRangePicker } from '@tremor/react'
import { FilterStateProvider } from '@/store/filter-state-context'
import { SwitchIQStateProvider } from '@/store/switchiq-api-context'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className + ' p-2'}>
        <FilterStateProvider>
          <SwitchIQStateProvider>
            <Header />
            {children}
          </SwitchIQStateProvider>
        </FilterStateProvider>
      </body>
    </html>
  )
}
